project_name: take

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/take
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    binary: take-cli

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - scripts/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

brews:
  - name: take
    homepage: "https://github.com/deblasis/take"
    description: "Cross-platform implementation of the ZSH take command"
    license: "MIT"
    tap:
      owner: deblasis
      name: homebrew-tap
    install: |
      bin.install "take-cli"
      bash_completion.install "completions/take.bash" => "take"
      zsh_completion.install "completions/take.zsh" => "_take"
      fish_completion.install "completions/take.fish"

scoop:
  bucket:
    owner: deblasis
    name: scoop-bucket
  homepage: "https://github.com/deblasis/take"
  description: "Cross-platform implementation of the ZSH take command"
  license: MIT

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/deblasis/take
    description: "Cross-platform implementation of the ZSH take command"
    maintainer: Alessandro De Blasis <alex@deblasis.net>
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - git
    recommends:
      - bash
    suggests:
      - zsh