name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          package-name: take
          token: ${{ secrets.GITHUB_TOKEN }}

  goreleaser:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
          cache: true

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}

  homebrew:
    needs: [release-please, goreleaser]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: deblasis/homebrew-tap
          token: ${{ secrets.TAP_GITHUB_TOKEN }}

      - name: Update Homebrew formula
        run: |
          version="${{ needs.release-please.outputs.tag_name }}"
          version="${version#v}"
          sed -i "s/version \".*\"/version \"$version\"/" Formula/take.rb
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Formula/take.rb
          git commit -m "chore: update take to $version"
          git push